CREATE DATABASE PIZZARIA
GO

USE PIZZARIA
GO

USE MASTER DROP DATABASE PIZZARIA

CREATE TABLE PIZZA (
ID                  INT                 NOT NULL,
PRIMARY KEY(ID)


)

CREATE TABLE PIZZASALGADA (
ID_PIZZA_SAL        INT                 NOT NULL,
SABOR               VARCHAR(40)         NOT NULL,
BORDA               VARCHAR(20)         NOT NULL,
PREÇO               DECIMAL(7, 2)       NOT NULL
PRIMARY KEY(ID_PIZZA_SAL)
FOREIGN KEY(ID_PIZZA_SAL) REFERENCES PIZZA(ID)
)

CREATE TABLE PIZZADOCE (
ID_PIZZA_DOCE       INT                 NOT NULL,
COBERTURA           VARCHAR(40)         NOT NULL,
BORDA               VARCHAR(20)         NOT NULL,
PREÇO               DECIMAL(7, 2)       NOT NULL
PRIMARY KEY(ID_PIZZA_DOCE)
FOREIGN KEY(ID_PIZZA_DOCE) REFERENCES PIZZA(ID)
)


SELECT *
FROM PIZZASALGADA

SELECT *
FROM PIZZA

SELECT *
FROM PIZZADOCE


